/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TableImport } from './routes/table'
import { Route as IndexImport } from './routes/index'
import { Route as TestLoadingImport } from './routes/test/loading'

// Create/Update Routes

const TableRoute = TableImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestLoadingRoute = TestLoadingImport.update({
  id: '/test/loading',
  path: '/test/loading',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableImport
      parentRoute: typeof rootRoute
    }
    '/test/loading': {
      id: '/test/loading'
      path: '/test/loading'
      fullPath: '/test/loading'
      preLoaderRoute: typeof TestLoadingImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/test/loading': typeof TestLoadingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/test/loading': typeof TestLoadingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/table': typeof TableRoute
  '/test/loading': typeof TestLoadingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/table' | '/test/loading'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/table' | '/test/loading'
  id: '__root__' | '/' | '/table' | '/test/loading'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TableRoute: typeof TableRoute
  TestLoadingRoute: typeof TestLoadingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TableRoute: TableRoute,
  TestLoadingRoute: TestLoadingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/table",
        "/test/loading"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/table": {
      "filePath": "table.tsx"
    },
    "/test/loading": {
      "filePath": "test/loading.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
